version: '{build}'

os: Visual Studio 2015

environment:
  matrix:
    - compiler: msvc-16-seh
      generator: "Visual Studio 16 2019"
      build_system: cmake
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019

matrix:
  fast_finish: true

configuration: Release

build:
  verbosity: minimal

install:
  - ps: |
      Write-Output "Env: $env"
      Write-Output "Env:Compiler: $env:compiler"
      Write-Output "Env:Generator: $env:generator"
      Write-Output "Env:Configuation: $env:configuration"

      # Download googletest
      appveyor DownloadFile https://github.com/google/googletest/archive/release-1.10.0.tar.gz -FileName release-1.10.0.tar.gz
      tar -xzf release-1.10.0.tar.gz

      $env:gtest = Resolve-Path "./googletest-release-1.10.0"
      Write-Output "Env:gtest: $env:gtest"

before_build:
  - ps: |
      # Build googletest
      cd $env:gtest
      md build
      cd build

      $env:buildtype = if ($env:generator -eq "MinGW Makefiles") {"-DCMAKE_BUILD_TYPE=$env:configuration"} else {"-DCMAKE_CONFIGURATION_TYPES=Debug;Release"}

      & cmake .. -G "$env:generator" $env:buildtype -Dgtest_force_shared_crt=ON
      & cmake --build . --config $env:configuration
      & cmake --install . --prefix ../install

      cd ../..
      Get-Location

build_script:
  - ps: |
      md build
      cd build

      & cmake .. -G "$env:generator" $env:buildtype -DGTest_DIR="$env:gtest/install/lib/cmake/GTest"
      & cmake --build . --config $env:configuration

test_script:
  - ps: |
      & ctest --verbose
