version: '{build}'

environment:
  matrix:
    - compiler: msvc-16-seh
      generator: "Visual Studio 16 2019 Win64"
      build_system: cmake
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019

    - compiler: msvc-15-seh
      generator: "Visual Studio 15 2017 Win64"
      build_system: cmake
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017

    - compiler: msvc-14-seh
      generator: "Visual Studio 14 2015 Win64"
      build_system: cmake
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015

configuration: Release

build:
  verbosity: minimal

install:
  - ps: |
      Write-Output "Compiler: $env:compiler"
      Write-Output "Generator: $env:generator"
      Write-Output "Env:Configuation: $env:configuration"
      Write-Output "Env: $env"

      # Download googletest
      appveyor DownloadFile https://github.com/google/googletest/archive/release-1.10.0.tar.gz -FileName googletest.tar.gz
      tar -xzf googletest.tar.gz
      ls
      pwd
      $GTEST_DIR = Resolve-Path "./googletest"



before_build:
  - ps: |
      $env:root=$env:APPVEYOR_BUILD_FOLDER
      Write-Output "env:root: $env:root"

build_script:
  - ps: |

test_script:
  - ps: |
